# Generated by Django 2.1.4 on 2018-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(blank=True, default='False', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verificaton',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
